# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'devtools://*')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{upstream_browser_version_short}`: The
# corresponding Safari/Chrome   version, but only with its major
# version. * `{qutebrowser_version}`: The currently running qutebrowser
# version.  The default value is equal to the default user agent of
# QtWebKit/QtWebEngine, but with the `QtWebEngine/...` part removed for
# increased compatibility.  Note that the value read from JavaScript is
# always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:145.0) Gecko/20100101 Firefox/145.0', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{upstream_browser_version_short}`: The
# corresponding Safari/Chrome   version, but only with its major
# version. * `{qutebrowser_version}`: The currently running qutebrowser
# version.  The default value is equal to the default user agent of
# QtWebKit/QtWebEngine, but with the `QtWebEngine/...` part removed for
# increased compatibility.  Note that the value read from JavaScript is
# always the global value.
# Type: FormatString
# config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version_short} Safari/{webkit_version}', 'https://gitlab.gnome.org/*')

# Маскируемся под актуальный Chrome на Windows, чтобы сайты отдавали полную версию
# config.set('content.headers.user_agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36', 'https://*')
config.set('content.headers.user_agent', 
           'Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Gecko/20100101 Firefox/145.0', 
           'https://accounts.google.com/*')
# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow locally loaded documents to access remote URLs.
# Type: Bool
config.set('content.local_content_can_access_remote_urls', True, 'file:///home/semyon/.local/share/qutebrowser/userscripts/*')

# Allow locally loaded documents to access other local URLs.
# Type: Bool
config.set('content.local_content_can_access_file_urls', False, 'file:///home/semyon/.local/share/qutebrowser/userscripts/*')

c.url.searchengines = {
    'DEFAULT': 'https://google.com/search?q={}',
    'aw': 'https://wiki.archlinux.org/title/Special:Search?search={}',
    'ddg': 'https://duckduckgo.com/?q={}', 
    'yt': 'https://www.youtube.com/results?search_query={}'
}

c.editor.command = ['kitty', '-e', 'nvim', '{file}']


config.set('colors.webpage.darkmode.enabled', False, 'https://*.google.com/*')
c.colors.webpage.darkmode.enabled = True
c.colors.webpage.preferred_color_scheme = 'dark'


# Enable smooth scrolling
c.scrolling.smooth = True


# Hide the window decoration (title bar) for a cleaner look in tiling window managers
c.window.hide_decoration = False

c.url.start_pages = ['file:///home/semyon/.config/qutebrowser/startpage/index.html']
c.url.default_page = 'file:///home/semyon/.config/qutebrowser/startpage/index.html'

c.qt.args = [
    'enable-gpu-rasterization',
    'ignore-gpu-blocklist',
    'enable-zero-copy',
    'enable-features=vaapiignoredriverchecks,vaapivideodecoder,acceleratedvideodecoder,acceleratedvideodecodelinuxgl,acceleratedvideoencoder,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,FluentOverlayScrollbar,MiddleClickAutoscroll',
   'enable-experimental-web-platform-features',
#   'disable-gpu-memory-buffer-video-frames=false',


]
#c.qt.environ = {"QTWEBENGINE_FORCE_USE_GBM": "0" }

c.auto_save.session = True

import os
os.environ["QT_QPA_PLATFORM"] = "wayland"

c.content.webgl = True 
c.content.canvas_reading = True
c.content.autoplay = False

c.content.javascript.clipboard= "access" # не совсем про это, но полезно
c.input.insert_mode.auto_load = False


c.session.lazy_restore = True

import subprocess

# Запускаем bash-скрипт в фоновом режиме, чтобы он не тормозил запуск браузера
subprocess.Popen(['/bin/bash', '/usr/local/bin/rbw-unlock.sh'])

c.content.pdfjs = True

# --- styles -----
import catppuccin
config.load_autoconfig(False)#
catppuccin.setup(c, 'mocha', True) # 'latte', 'frappe', 'macchiato', 'mocha'

c.tabs.padding = {'bottom': 5, 'left': 5, 'right': 5, 'top': 5}
c.statusbar.padding = {'bottom': 5, 'left': 5, 'right': 5, 'top': 5}

c.fonts.default_family = 'JetBrains Mono' # Твой любимый моноширинный шрифт
c.fonts.default_size = '10pt'

# Шрифты для веба (чтобы сайты выглядели чисто)
c.fonts.web.family.standard = 'Inter'
c.fonts.web.family.sans_serif = 'Inter'
c.fonts.web.family.fixed = 'JetBrains Mono'


# ---- binds ----

config.unbind('.')
config.unbind('<Ctrl+v>')
config.bind('I', "mode-enter passthrough")

config.unbind('J')
config.unbind('K')
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')

config.unbind('gJ')
config.unbind('gK')
config.bind('gJ', 'tab-move -')
config.bind('gK', 'tab-move +')

# k - мгновенный скролл вниз (без инерции)
config.bind('k', 'cmd-run-with-count 2 scroll up')

# j - мгновенный скролл вверх (без инерции)
config.bind('j', 'cmd-run-with-count 2 scroll down')

#config.unbind('j', mode='normal')
#config.unbind('k', mode='normal')



config.bind('<Escape>', 'fake-key <Escape> ;; jseval -q document.activeElement.blur()')
# config.bind('<Escape>', 'jseval -q document.activeElement.blur()', mode='normal')

config.bind('zl', 'spawn --userscript bw-fill')
config.bind('zs', 'spawn --userscript bw-save')
config.bind('zr', 'spawn --userscript bw-reload')

# 1. Основные буквы (йцукен -> qwerty)
russian = 'йцукенгшщзфывапролдячсмить'
english = 'qwertyuiopasdfghjklzxcvbnm'

# 2. Спецсимволы Shift + Цифры (на RU раскладке они другие)
# RU: ! " № ; % : ? * ( ) _ +
# EN: ! @ # $ % ^ & * ( ) _ +
ru_shift_alt = '!"№;%:?хъХЪжЖэЭбБюЮ.,ёЁ'
en_shift_alt = '!@#$%^&[]{};:\'",<.>/?`~'

# Заполняем словарь маппингов
for r, e in zip(russian, english):
    c.bindings.key_mappings[r] = e
    c.bindings.key_mappings[r.upper()] = e.upper()

for r, e in zip(ru_shift_alt, en_shift_alt):
    c.bindings.key_mappings[r] = e

# 3. Фикс для запятой и точки (в RU они на одной клавише рядом с Shift)
# Это позволит Ctrl+. и Ctrl+, работать корректно
# c.bindings.key_mappings['/'] = '.'
# c.bindings.key_mappings['?'] = ','


# ---- add block ----

# Использовать оба метода блокировки
c.content.blocking.method = 'both'

# Расширенные списки фильтров
c.content.blocking.adblock.lists = [
    "https://easylist.to/easylist/easylist.txt",
    "https://easylist.to/easylist/easyprivacy.txt",
    "https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt",
    "https://secure.fanboy.co.nz/fanboy-cookiemonster.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt",
]


