cursor #e1e4d9
cursor_text_color #c4c8bb

foreground            #e1e4d9
background            #11140e
selection_foreground  #283420
selection_background  #bdcbaf
url_color             #abd28f

color0   #11140e
color1   #f1856c
color2   #6fd269
color3   #ffec72
color4   #9bc77b
color5   #406128
color6   #abd28f
color7   #d4dccf
color8   #82887e
color9   #ffb19f
color10  #a9fba3
color11  #fff3a5
color12  #c2e7a8
color13  #ddffc6
color14  #e9ffda
color15  #fbfff8
