enable_audio_bell no
window_alert_on_bell no

#Fonts
#font_family FiraCode Nerd Font
#font_family JetBrains Mono
font_family family="JetBrainsMono Nerd Font"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13

# url
detect_urls yes
# url_color #ffff00
url_style straight
open_url_with default

# Theme
# background #1b1b27
# selection_background #ffffff
background_opacity 0.7

# dynamic_background_opacity yes
# background_blur 1 
# active_border_color #7AA2F7
# inactive_border_color #000000

# window padding
# window_margin_width 4

hide_window_decorations yes

# tabs
tab_bar_edge top
tab_bar_margin_width 1.0
tab_bar_margin_height 1.0 0.5
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}"

# styling tabs
active_tab_foreground #0da38a 
active_tab_background #1d202f
active_tab_font_style bold-italic
inactive_tab_foreground #ffffff
inactive_tab_background #292945
inactive_tab_font_style normal

# clipboard
map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard

map ctrl+с copy_and_clear_or_interrupt
map ctrl+м paste_from_clipboard


map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+с copy_to_clipboard
map ctrl+shift+м paste_from_clipboard

# keymaps
# map ctrl+shift+i next_layout
# map ctrl+enter new_window
# map ctrl+shift+l next_window
# map ctrl+shift+h previous_window

# map ctrl+t new_tab
# map ctrl+w close_tab


map ctrl+shift+f5 load_config_file



# == Soft Cursor ==
# Choose a softer shape. 'beam' or 'underline' feel much lighter than 'block'
cursor_shape beam
cursor_beam_thickness 1.5

# The magic setting for a soft pulse. 'ease-in-out' makes it fade smoothly.
cursor_blink_interval 0.6 ease-in-out

# == Cursor Trail (Kitty's best visual feature) ==
# Adds a smooth comet-like trail when the cursor moves or when you type
cursor_trail 1
# How fast the trail fades out (first number is background, second is foreground)
cursor_trail_decay 0.1 0.4
